name: Deploy

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - master

concurrency:
  group: seaql.github.io
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          key: ${{ github.repository }}-${{ github.ref_name }}
          path: |
            ~/.npm
            SeaORM/node_modules
            SeaORM/.docusaurus
            SeaORM/build
            Blog/node_modules
            Blog/.docusaurus
            Blog/build
            Seaography/node_modules
            Seaography/.docusaurus
            Seaography/build
            SeaStreamer/node_modules
            SeaStreamer/.docusaurus
            SeaStreamer/build

      - id: git-log
        run: echo "message=$(git log --no-merges -1 --oneline)" >> $GITHUB_OUTPUT

      - run: echo $GITHUB_OUTPUT

      - if: ${{ contains(steps.git-log.outputs.message, '[SeaORM]') || contains(steps.git-log.outputs.message, '[full]') }}
        run: sh build-site.sh SeaORM SeaORM

      - if: ${{ contains(steps.git-log.outputs.message, '[blog]') || contains(steps.git-log.outputs.message, '[full]') }}
        run: sh build-site.sh Blog blog

      - if: ${{ contains(steps.git-log.outputs.message, '[Seaography]') || contains(steps.git-log.outputs.message, '[full]') }}
        run: sh build-site.sh Seaography Seaography

      - if: ${{ contains(steps.git-log.outputs.message, '[SeaStreamer]') || contains(steps.git-log.outputs.message, '[full]') }}
        run: sh build-site.sh SeaStreamer SeaStreamer

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: false
          clean-exclude: preview
